# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.yarn=1.21.10+build.2
build.fabric_api=0.135.0+1.21.10

# Additional Dependencies Properties
# simple-voice-chat, check https://modrinth.com/mod/simple-voice-chat/versions?g=1.21.10&l=fabric
dep.simple-voice-chat=fabric-1.21.10-2.6.0
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.10&l=fabric
dep.modmenu=16.0.0-rc.1
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.10&l=fabric
dep.yacl=3.8.0+1.21.9-fabric
# plasmo-voice, check https://modrinth.com/mod/plasmo-voice/versions?g=1.21.10&l=fabric
dep.plasmo-voice=fabric-1.21.9-2.1.6