import net.lopymine.utils.MossyUtils

plugins {
	id "net.lopymine.mossy-plugin-core" version "$mossy_plugin_version"
}

mossyDependencies {

	minecraft = stonecutter.current.version.toString()
	lombok = prop("base.lombok_version")

	fabricApi = prop("build.fabric_api")
	fabricLoader = prop("build.fabric_loader")

	forge = prop("build.forge")

	neoForge = prop("build.neoforge")
	parchment = prop("build.parchment")

	additional {
		//override("modCompileOnly", "yacl")
		disable("plasmo-voice")
		disable("simple-voice-chat")
	}

}

repositories {

	mavenCentral()

	// Plasmo Voice
	maven {
		name = 'plasmoverse-releases'
		url = 'https://repo.plasmoverse.com/releases'
	}
	maven {
		name = 'plasmoverse-snapshots'
		url = 'https://repo.plasmoverse.com/snapshots'
	}

	// Simple Voice
	maven {
		name = "henkelmax.public"
		url = 'https://maven.maxhenkel.de/repository/public'
	}

	//TODO: hmm, CustomModels?
// 	maven {
//		name = "tom5454 maven"
//		url = "https://raw.githubusercontent.com/tom5454/maven/main"
//	}

}

dependencies {

	if (prop("dep.plasmo-voice") != "unknown") {
		if (prop("dep.plasmo-voice").contains("SNAPSHOT")) {
			implementation("su.plo.voice.api:client:${MossyUtils.substringSinceLast(prop("dep.plasmo-voice"), "-") + "-SNAPSHOT"}")
		} else {
			implementation("su.plo.voice.api:client:${MossyUtils.substringSinceLast(prop("dep.plasmo-voice"), "-")}")
		}
	}

	if (prop("dep.simple-voice-chat").contains("+")) {
		implementation("de.maxhenkel.voicechat:voicechat-api:${MossyUtils.substringBefore(MossyUtils.substringSince(prop("dep.simple-voice-chat"), "-"), "+")}")
	} else {
		implementation("de.maxhenkel.voicechat:voicechat-api:${MossyUtils.substringSinceLast(prop("dep.simple-voice-chat"), "-")}")
	}

//	modImplementation("me.lucko:fabric-permissions-api:${prop("dep.fabric-permissions-api")}")

	// TODO: hmm, CustomModels?
//    implementation ("com.tom5454.cpm:CustomPlayerModels-API:0.6.21a")
//    implementation ("com.tom5454.cpm:CustomPlayerModels-Fabric-0.6.21a:0.6.21a")
}

mossyResources {
	//	expandFiles = ["file pattern"]
	customProperty("plasmo_voice", prop("dep.plasmo-voice"))
	customProperty("simple_voice_chat", prop("dep.simple-voice-chat"))
}

String prop(String key) {
	return findProperty(key).toString()
}