# # # # # # # # # # # # # #
#    Gradle Properties    #
# # # # # # # # # # # # # #

current_mossy_build_version = 1.0.0

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx16G
org.gradle.parallel=true

# Stonecutter
dev.kikugie.stonecutter.hard_mode=true

# Mod Properties
data.mod_id = talkingheads
data.mod_name = Talking Heads
data.mod_version = 1.0.10
data.mod_group = me.zipestudio.talkingheads
data.mod_maven_group = me.zipestudio

data.mod_description = Addon for PlasmoVoice & SimpleVoiceChat, that scales player heads when they're talking.
data.mod_authors = ZipeStudio
data.mod_license = CC-BY-ND 4.0

# Main Dependencies
base.lombok_version = 1.18.32

# Multi-Versions Properties
# Verified version: 1.20.1 1.20.4 1.21 1.21.1 1.21.2 1.21.3 1.21.4 1.21.5 1.21.6 1.21.7 1.21.8
multi_versions = 1.20.1 1.20.4 1.21 1.21.1 1.21.2 1.21.3 1.21.4 1.21.5 1.21.6 1.21.7 1.21.8 1.21.9 1.21.10

# Build Dependencies
build.yarn = [VERSIONED]
build.fabric_loader = 0.17.2
build.fabric_api = [VERSIONED]
build.java = [VERSIONED]

# Additional Dependencies, "dep." is important
dep.yacl = [VERSIONED]
dep.modmenu = [VERSIONED]
dep.plasmo-voice = [VERSIONED]
dep.simple-voice-chat = [VERSIONED]

# # # # # # # # # # # # # #
#  Publication Properties #
# # # # # # # # # # # # # #

# Mod Loaders
loaders = fabric
# Versions Specifications
versions_specifications = 1.20.1[1.20.2] 1.21[2]
# Version Type [RELEASE, BETA, ALPHA]
version_type = RELEASE

# Imitation of Publishing. Set to "true" for testing
test_publish = false

# Project IDs
modrinth_id = Os35nfkh
curseforge_id = 1108100

# CurseForge Settings
is_for_client = true
is_for_server = false
max_java_version = 21

# Mod Depends
depends_requires = fabric-api
depends_optional = modmenu yacl plasmo-voice simple-voice-chat
depends_incompatible = none
depends_embeds  = none
