# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=26.1.2.48-beta

# Additional Dependencies Properties
# simple-voice-chat, check https://modrinth.com/mod/simple-voice-chat/versions?g=26.1&l=neoforge
dep.simple-voice-chat=neoforge-2.6.13+26.1
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.1&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.1&l=neoforge
dep.yacl=3.9.3+26.1-neoforge
# plasmo-voice, check https://modrinth.com/mod/plasmo-voice/versions?g=26.1&l=neoforge
dep.plasmo-voice=neoforge-26.1-2.1.9
