# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=20.4.251
build.parchment=2024.04.14

# Additional Dependencies Properties
# simple-voice-chat, check https://modrinth.com/mod/simple-voice-chat/versions?g=1.20.4&l=neoforge
dep.simple-voice-chat=neoforge-1.20.4-2.5.0
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.20.4&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.20.4&l=neoforge
dep.yacl=3.6.6+1.20.4-neoforge
# plasmo-voice, check https://modrinth.com/mod/plasmo-voice/versions?g=1.20.4&l=neoforge
dep.plasmo-voice=unknown