# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=21.9.16-beta
build.parchment=2025.10.05

# Additional Dependencies Properties
# simple-voice-chat, check https://modrinth.com/mod/simple-voice-chat/versions?g=1.21.9&l=neoforge
dep.simple-voice-chat=neoforge-1.21.9-2.6.0
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.9&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.9&l=neoforge
dep.yacl=3.8.0+1.21.9-neoforge
# plasmo-voice, check https://modrinth.com/mod/plasmo-voice/versions?g=1.21.9&l=neoforge
dep.plasmo-voice=neoforge-1.21.9-2.1.6
