# Versioned Properties

# Fabric Properties, check https://fabricmc.net/develop/
build.yarn=1.21.1+build.3
build.fabric_api=0.115.1+1.21.1

# Additional Dependencies Properties
# plasmo-voice, check https://modrinth.com/mod/plasmo-voice/versions?g=1.21.1
dep.plasmo-voice=fabric-1.21-2.1.3
# simple-voice-chat, check https://modrinth.com/mod/simple-voice-chat/versions?g=1.21.1
dep.simple-voice-chat=fabric-1.21.1-2.5.27
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.1
dep.modmenu=11.0.3
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.1
dep.yacl=3.6.1+1.21-fabric
