# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.92.9+1.20.1

# Additional Dependencies Properties
# simple-voice-chat, check https://modrinth.com/mod/simple-voice-chat/versions?g=1.20.1&l=fabric
dep.simple-voice-chat=fabric-1.20.1-2.5.27
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.20.1&l=fabric
dep.modmenu=7.2.2
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.20.1&l=fabric
dep.yacl=3.6.5+1.20.1-fabric
# plasmo-voice, check https://modrinth.com/mod/plasmo-voice/versions?g=1.20.1&l=fabric
dep.plasmo-voice=fabric-1.20.1-2.1.3
