# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.yarn=1.21.6+build.1
build.fabric_api=0.128.0+1.21.6

# Additional Dependencies Properties
# plasmo-voice, check https://modrinth.com/mod/plasmo-voice/versions?g=1.21.6&l=fabric
dep.plasmo-voice=fabric-1.21.5-2.1.4
# simple-voice-chat, check https://modrinth.com/mod/simple-voice-chat/versions?g=1.21.6&l=fabric
dep.simple-voice-chat=fabric-1.21.6-2.5.31
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.6&l=fabric
dep.modmenu=15.0.0-beta.3
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.6&l=fabric
dep.yacl=3.7.1+1.21.6-fabric

