# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=21.7.25-beta
build.parchment=2025.07.18

# Additional Dependencies Properties
# simple-voice-chat, check https://modrinth.com/mod/simple-voice-chat/versions?g=1.21.7&l=neoforge
dep.simple-voice-chat=neoforge-1.21.7-2.5.31
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.7&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.7&l=neoforge
dep.yacl=3.7.1+1.21.6-neoforge
# plasmo-voice, check https://modrinth.com/mod/plasmo-voice/versions?g=1.21.7&l=neoforge
dep.plasmo-voice=neoforge-1.21.6-2.1.5
