# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.153.0+26.2

# Additional Dependencies Properties
# simple-voice-chat, check https://modrinth.com/mod/simple-voice-chat/versions?g=26.2&l=fabric
dep.simple-voice-chat=fabric-2.6.20+26.2
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.2&l=fabric
dep.modmenu=20.0.0-beta.4
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.2&l=fabric
dep.yacl=3.9.4+26.2-fabric
# plasmo-voice, check https://modrinth.com/mod/plasmo-voice/versions?g=26.2&l=fabric
dep.plasmo-voice=fabric-26.2-2.1.11
